language: node_js
node_js:
  - 14
dist: trusty
services:
  - mognodb
  - redis-server
env:
  - NODE_ENV=test PORT=8000 ACCESS_TOKEN_EXPIRES_IN=1d
  - ACCESS_TOKEN_EXPIRES_IN_SEC=86400
  - JWT_SECRET=myjwtsecretmyjwtsecret
  - REFRESH_TOKEN_EXPIRES_IN=60d
  - REFRESH_TOKEN_EXPIRES_IN_SEC=5184000
  - SALTROUNDS=10
cache:
  directories:
    - node_modules
    - client/node_modules
install:
  - npm install
script:
  - nohup npm run start &
  - sleep 3
  - npm run test:integration
