sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t osiris65/honya-backend -f Dockerfile.dev .

script:
  - docker run osiris65/honya-backend npm run test

deploy:
  provider: elasticbeanstalk
  region: 'us-east-2'
  app: 'honya-backend'
  env: 'Honyabackend-env-1'
  bucket_name: 'elasticbeanstalk-us-east-2-302362783199'
  bucket_path: 'honya-backend'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY