language: node_js
node_js:
  - 14
dist: trusty
services:
  - mognodb
  - redis-server
env:
  - NODE_ENV=ci PORT=8000
cache:
  directories:
    - node_modules
    - client/node_modules
install:
  - npm install
script:
  - nohup npm run start &
  - sleep 3
  - npm run test:integration
