version: '3.9'
services:
  redis:
    image: 'redis'
  mongo:
    image: 'mongo:4.4.7'
    volumes:
      - /data/mongodb:/data/db
    ports:
      - "27017:27017"
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - '80:80'
    depends_on:
      - api
  api:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./server:/app
    environment:
      - GOOGLE_OAUTH_CLIENT_ID=[key]
      - GOOGLE_OAUTH_CLIENT_SECRET=[key]
      - GOOGLE_OAUTH_CALLBACK_URL=http://localhost/api/v1/auth/google/callback
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - JWT_SECRET=myjwtsecret
      - ACCESS_TOKEN_EXPIRES_IN=1d
      - ACCESS_TOKEN_EXPIRES_IN_SEC=86400
      - REFRESH_TOKEN_EXPIRES_IN=60d
      - REFRESH_TOKEN_EXPIRES_IN_SEC=5184000
      - SALTROUNDS=10
    depends_on:
      - redis
      - mongo