version: '3.9'
services:
  redis:
    image: 'redis'
    networks:
      - honya
  mongo:
    image: 'mongo'
    networks:
      - honya
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - '80:80'
    depends_on:
      - api
    networks:
      honya:
        aliases:
          - honya.co.jp
  web:
    build:
      context: ./web
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./web:/app
    depends_on:
      - api
    networks:
      - honya
  api:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./server:/app
    environment:
      - GOOGLE_OAUTH_CLIENT_ID=765177302336-ppho0d0i2qkotm1290f1k92qp68bqcpa.apps.googleusercontent.com
      - GOOGLE_OAUTH_CLIENT_SECRET=mH1JWxacesVCPEz7EK80TfRj
      - GOOGLE_OAUTH_CALLBACK_URL=http://localhost/api/v1/auth/google/callback
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - BRAINTREE_MERCHANT_ID=cv4sxp66w4xnm59b
      - BRAINTREE_PUBLIC_KEY=bf5438dz7f6krw9w
      - BRAINTREE_PRIVATE_KEY=b195ff1685bcc3a2654573ad46f2cd26
      - JWT_SECRET=myjwtsecret
      - ACCESS_TOKEN_EXPIRES_IN=1d
      - ACCESS_TOKEN_EXPIRES_IN_SEC=86400
      - REFRESH_TOKEN_EXPIRES_IN=60d
      - REFRESH_TOKEN_EXPIRES_IN_SEC=5184000
      - SALTROUNDS=10
      - NEXT_PUBLIC_API_PREFIX=/api/v1
      - NEXT_PUBLIC_API_HOST=honya.co.jp
    depends_on:
      - redis
      - mongo
    networks:
      - honya
networks:
  honya:
    driver: bridge      