version: '3.9'
services:
  redis:
    image: 'redis'
  mongo:
    image: 'mongo:4.4.7'
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - '80:80'
    depends_on:
      - api
  api:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./server:/app
    environment:
      - GOOGLE_OAUTH_CLIENT_ID
      - GOOGLE_OAUTH_CLIENT_SECRET
      - GOOGLE_OAUTH_CALLBACK_URL  
      - MONGO_HOST
      - MONGO_PORT
      - REDIS_HOST
      - REDIS_PORT
      - JWT_SECRET
      - ACCESS_TOKEN_EXPIRES_IN=1d
      - ACCESS_TOKEN_EXPIRES_IN_SEC=86400
      - REFRESH_TOKEN_EXPIRES_IN=60d
      - REFRESH_TOKEN_EXPIRES_IN_SEC=5184000
      - SALTROUNDS=10      
    depends_on:
      - redis
      - mongo