version: '3.9'
services:
  redis:
    image: 'redis'
    networks:
      - honya
  mongo:
    image: 'mongo'
    networks:
      - honya
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - '80:80'
    depends_on:
      - api
    networks:
      honya:
        aliases:
          - honya.co.jp
  web:
    build:
      context: ./web
      dockerfile: Dockerfile.dev
    image: osiris65/honya-web-0-1-0
    container_name: honya-web
    volumes:
      - /app/node_modules
      - ./web:/app
    depends_on:
      - api
    networks:
      - honya
  api:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./server:/app
    environment:
      - GOOGLE_OAUTH_CLIENT_ID
      - GOOGLE_OAUTH_CLIENT_SECRET
      - GOOGLE_OAUTH_CALLBACK_URL
      - MONGO_HOST
      - MONGO_PORT
      - REDIS_HOST
      - REDIS_PORT
      - BRAINTREE_MERCHANT_ID
      - BRAINTREE_PUBLIC_KEY
      - BRAINTREE_PRIVATE_KEY
      - JWT_SECRET
      - ACCESS_TOKEN_EXPIRES_IN=1d
      - ACCESS_TOKEN_EXPIRES_IN_SEC=86400
      - REFRESH_TOKEN_EXPIRES_IN=60d
      - REFRESH_TOKEN_EXPIRES_IN_SEC=5184000
      - SALTROUNDS=10
      - NEXT_PUBLIC_API_PREFIX=/api/v1
      - NEXT_PUBLIC_API_HOST=honya.co.jp
    depends_on:
      - redis
      - mongo
    networks:
      - honya
networks:
  honya:
    driver: bridge      