version: '3.9'
services:
  redis:
    image: 'redis'
  mongo:
    image: 'mongo'
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    volumes:
      - /app/node_modules
      - .:/app
    command: bash -c 'echo $MONGO_HOST'
    environment:
      - MONGO_HOST=$MONGO_HOST
      - MONGO_PORT=$MONGO_PORT
      - REDIS_HOST=$$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
      - JWT_SECRET=$JWT_SECRET
      - ACCESS_TOKEN_EXPIRES_IN=1d
      - ACCESS_TOKEN_EXPIRES_IN_SEC=86400
      - REFRESH_TOKEN_EXPIRES_IN=60d
      - REFRESH_TOKEN_EXPIRES_IN_SEC=5184000
      - SALTROUNDS=10      
    depends_on:
      - redis
      - mongo