version: '3.9'
services:
  mongo:
    image: 'mongo:4.4.7'
    restart: always
    mem_limit: 128m
    volumes:
      - db-data:/data/db
  nginx:
    image: 'osiris65/honya-nginx-0-1-0'
    restart: always
    ports:
      - '80:80'
    mem_limit: 128m
    links:
      - api
    depends_on:
      - api
  api:
    image: 'osiris65/honya-server-0-1-0'
    mem_limit: 128m
    environment:
      - MONGO_HOST
      - MONGO_PORT
      - REDIS_HOST
      - REDIS_PORT
      - JWT_SECRET
      - ACCESS_TOKEN_EXPIRES_IN=1d
      - ACCESS_TOKEN_EXPIRES_IN_SEC=86400
      - REFRESH_TOKEN_EXPIRES_IN=60d
      - REFRESH_TOKEN_EXPIRES_IN_SEC=5184000
      - SALTROUNDS=10
    depends_on:
      - mongo

volumes:
  db-data:
