version: '3.9'
services:
  redis:
    image: 'redis'
    networks:
      - honya
  mongo:
    image: 'mongo'
    restart: always
    mem_limit: 128m
    volumes:
      - db-data:/data/db
    networks:
      - honya
  nginx:
    image: 'osiris65/honya-nginx-0-1-0'
    restart: always
    ports:
      - '80:80'
    mem_limit: 128m
    links:
      - api
    depends_on:
      - api
    networks:
      - honya
  web:
    image: 'osiris65/honya-web-0-1-0'
    mem_limit: 128m
    depends_on:
      - api
    networks:
      - honya
  api:
    image: 'osiris65/honya-server-0-1-0'
    mem_limit: 128m
    environment:
      - MONGO_HOST
      - MONGO_PORT
      - REDIS_HOST
      - REDIS_PORT
      - JWT_SECRET
      - ACCESS_TOKEN_EXPIRES_IN=1d
      - ACCESS_TOKEN_EXPIRES_IN_SEC=86400
      - REFRESH_TOKEN_EXPIRES_IN=60d
      - REFRESH_TOKEN_EXPIRES_IN_SEC=5184000
      - SALTROUNDS=10
      - BRAINTREE_MERCHANT_ID
      - BRAINTREE_PUBLIC_KEY
      - BRAINTREE_PRIVATE_KEY
    depends_on:
      - mongo
    networks:
      - honya
volumes:
  db-data:
networks:
  honya:
    driver: bridge