version: '3.9'
services:
  redis:
    image: 'redis'
    networks:
      - honya
  mongo:
    image: 'mongo'
    restart: always
    mem_limit: 128m
    volumes:
      - db-data:/data/db
    networks:
      - honya
  nginx:
    image: 'osiris65/honya-nginx-0-1-0'
    restart: always
    ports:
      - "80:80"
      - "443:443"
    mem_limit: 128m
    volumes:
      - ./nginx/ssl:/etc/ssl/certs/nginx/
    links:
      - api
    depends_on:
      - api
    networks:
      - honya
  web:
    image: 'osiris65/honya-web-0-1-0'
    mem_limit: 128m
    depends_on:
      - api
    networks:
      - honya
  api:
    image: 'osiris65/honya-server-0-1-0'
    mem_limit: 128m
    environment:
      - GOOGLE_OAUTH_CLIENT_ID=[key]
      - GOOGLE_OAUTH_CLIENT_SECRET=[key]
      - GOOGLE_OAUTH_CALLBACK_URL=[key]
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - JWT_SECRET=[key]
      - ACCESS_TOKEN_EXPIRES_IN=1d
      - ACCESS_TOKEN_EXPIRES_IN_SEC=86400
      - REFRESH_TOKEN_EXPIRES_IN=60d
      - REFRESH_TOKEN_EXPIRES_IN_SEC=5184000
      - SALTROUNDS=10
      - BRAINTREE_MERCHANT_ID=[key]
      - BRAINTREE_PUBLIC_KEY=[key]
      - BRAINTREE_PRIVATE_KEY=[key]
    depends_on:
      - mongo
    networks:
      - honya
volumes:
  db-data:
networks:
  honya:
    driver: bridge