version: '3.9'
services:
  redis:
    image: 'redis'
    networks:
      - honya
  mongo:
    image: 'mongo:4.4.7'
    volumes:
      - honya-mongodb:/data/db
    ports:
      - "27017:27017"
    networks:
      - honya
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    image: osiris65/honya-nginx-0-1-0
    container_name: honya-nginx
    restart: always
    ports:
      - '80:80'
    depends_on:
      - api
    networks:
      honya:
        aliases:
          - honya.co.jp
  web:
    build:
      context: ./web
      dockerfile: Dockerfile.dev
    image: osiris65/honya-web-0-1-0
    container_name: honya-web
    volumes:
      - /app/node_modules
      - ./web:/app
    networks:
      - honya
  api:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    image: osiris65/honya-server-0-1-0
    container_name: honya-server
    volumes:
      - /app/node_modules
      - ./server:/app
    environment:
      - GOOGLE_OAUTH_CLIENT_ID=[key]
      - GOOGLE_OAUTH_CLIENT_SECRET=[key]
      - GOOGLE_OAUTH_CALLBACK_URL=http://localhost/api/v1/auth/google/callback
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - JWT_SECRET=myjwtsecret
      - ACCESS_TOKEN_EXPIRES_IN=1d
      - ACCESS_TOKEN_EXPIRES_IN_SEC=86400
      - REFRESH_TOKEN_EXPIRES_IN=60d
      - REFRESH_TOKEN_EXPIRES_IN_SEC=5184000
      - SALTROUNDS=10
    depends_on:
      - redis
      - mongo
    networks:
      - honya
volumes:
  honya-mongodb:
networks:
  honya:
    driver: bridge