FROM node:14.17.3-alpine

# Install PM2
# RUN npm install -g pm2

WORKDIR /app

COPY ./package.json ./
RUN npm install
COPY . .

EXPOSE 8000

# Default command
CMD ["npm", "run", "dev"]
# CMD ["pm2-runtime", "ecosystem.config.js"]