FROM nginx
COPY ./default.conf /etc/nginx/conf.d/default.conf
EXPOSE 80

# https://gist.github.com/hermanbanken/96f0ff298c162a522ddbba44cad31081
# https://stackoverflow.com/questions/57739560/what-do-i-need-to-change-in-nginx-official-dockers-image-to-have-the-set-misc-n
